CREATE REL TABLE  IMDB_BUSiNESS_CAST_HAS_NAME(FROM IMDB_BUSINESS_CAST TO IMDB_BUSINESS_NAME);
CREATE REL TABLE  IMDB_BUSiNESS_CAST_HAS_TITLE(FROM IMDB_BUSINESS_CAST TO IMDB_BUSINESS_TITLE);
CREATE REL TABLE  IMDB_BUSiNESS_NAME_KNOWN_FOR_TITLE(FROM OMDB_BUSINESS_CATEGORY TO IMDB_BUSINESS_TITLE);
CREATE REL TABLE  IMDB_BUSiNESS_TITLE_ALIAS_ALIASES_TITLE(FROM IMDB_BUSINESS_TITLE_ALIAS TO IMDB_BUSINESS_TITLE);
CREATE REL TABLE  IMDB_BUSiNESS_TITLE_HAS_DIRECTOR_NAME(FROM IMDB_BUSINESS_TITLE TO IMDB_BUSINESS_NAME);
CREATE REL TABLE  IMDB_BUSiNESS_TITLE_HAS_PARENT_TITLE(FROM IMDB_BUSINESS_TITLE TO IMDB_BUSINESS_TITLE);
CREATE REL TABLE  IMDB_BUSiNESS_TITLE_HAS_WRITER_NAME(FROM IMDB_BUSINESS_TITLE TO IMDB_BUSINESS_NAME);